#lang scheme
(require "basic.rkt")

;for 2.3
(provide variable?)
(provide same-variable?)
(provide sum?)
(provide addend)
(provide augend)
(provide make-sum)
(provide product?)
(provide multiplier)
(provide multiplicand)
(provide make-product)


(define (variable? x) (symbol? x))
(define (same-variable? v1 v2)
  (and (variable? v1)
       (variable? v2)
       (eq? v1 v2)))

(define (sum? e)
  (and (pair? e) (eq? (car e) '+)))
(define (addend e) (caddr e))
(define (augend e) (cadr e))
(define (=number? exp num)
  (and (number? exp) (= exp num)))
(define (make-sum a1 a2)
  (cond ((=number? a1 0) a2)
        ((=number? a2 0) a1)
        ((and (number? a1) (number? a2)) (+ a1 a2))
        (else (list '+ a1 a2))))

(define (product? e)
  (and (pair? e) (eq? (car e) '*)))
(define (multiplier e) (caddr e))
(define (multiplicand e) (cadr e))
(define (make-product m1 m2)
  (cond ((or (=number? m1 0) (=number? m2 0)) 0)
        ((=number? m1 1) m2)
        ((=number? m2 1) m1)
        ((and (number? m1) (number? m2)) (* m1 m2))
        (else (list '* m1 m2))))